title: 'RTFM Documentation'
default_lang: en
author:
  name: 'Evan Chute'
  email: wtf@evanchute.com
taxonomies:
  - category
  - tag
metadata:
  description: 'RTFM Skeleton'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
